# Numpy
it can see code

In [1]:
import numpy as np

In [3]:
x = np.array([2,3,5,7])
y =np.array([2,4,2,4])
x,y

(array([2, 3, 5, 7]), array([2, 4, 2, 4]))

Array is a vector

## Operation

In [4]:
x+y

array([ 4,  7,  7, 11])

In [5]:
x-y

array([ 0, -1,  3,  3])

In [6]:
x.T
#transport: maybe useful for dim>1 array

array([2, 3, 5, 7])

## Array is different from list

list can not be added directly


Array can do dot product and cross product!!!

In [7]:
xl = [2,3]
yl = [3,4]
xl + yl

[2, 3, 3, 4]

In [8]:
# dot product
a = x * y

In [11]:
a

array([ 4, 12, 10, 28])

In [12]:
# cross product
b = np.dot(x,y)
b

54

# shape

In [14]:
x.shape
# use to check the dimension of the array
# 所以这就是一个长度为4， 但只有一排的array
# 没写默认0

(4,)

In [16]:
np.dot(x,y).shape
# 这个就是1*1的array

()

# Matrices

In [33]:
A = np.array([
    [1,2],
    [3,4]
])
A

array([[1, 2],
       [3, 4]])

In [22]:
A.shape
#这是一个2*2的矩阵

(2, 2)

In [34]:
B = np.array([
    [1,2],
    [3,4]
])
B

array([[1, 2],
       [3, 4]])

In [26]:
# 然后可以对这两个矩阵做各种操作
# 矩阵乘法加法等等

In [27]:
A * B

array([[ 1,  4],
       [ 9, 16]])

In [36]:
A@B # 点乘
np.dot(A,B) # 也是点乘
# 7 = 1*1 +2*3

array([[ 7, 10],
       [15, 22]])

In [31]:
# linear algebra
np.linalg.det(A)

-2.0000000000000004

In [32]:
np.average(A)

2.5

# Special Array Initialization

In [38]:
A = np.zeros((6,6))
A

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
# 对角矩阵
C = np.diag((1,2,3))
C

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [46]:
# 单位矩阵
D = np.eye(5)
D

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
E = np.random.rand(3,3)
E

array([[0.90566788, 0.08705316, 0.42377442],
       [0.54668478, 0.17772241, 0.60610494],
       [0.67919919, 0.51964991, 0.14881299]])

In [53]:
F = np.tri(3) # 自动生成一个下三角矩阵
F

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [55]:
G = np.triu(B) # 找到一个矩阵B的上三角矩阵
G

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

# Array type

In [56]:
A = np.ones((3,3))
A.size,A.ndim,A.dtype
# 其中含有的数字个数 #ndim是number of dimension

(9, 2, dtype('float64'))

# Casting

In [61]:
E = A.astype("float32") #把一个矩阵的数据类型转化成另一个
E.dtype
# 也可以转成int

dtype('float32')

# Array rearrange

In [64]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
AA = np.reshape(A,(6,1))# 先写的是列数！！！
AA

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Attention!!!
[[1,2,3]]和[1,2,3]是不一样的

前面的是(3:)后面是(3:1)

In [69]:
A.ravel() #把一个矩阵压成一维

array([1, 2, 3, 4, 5, 6])

In [71]:
A = np.ones((3,3,3,3))
A
# 四维矩阵啊啊啊啊啊啊啊啊

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [75]:
AA = A.reshape((3,3,-1))
AA # 把四维矩阵压成三维的阿阿阿阿阿阿好难

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [76]:
AAA = AA.reshape((3,3,-1))
AAA 

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

# Broadingcasting

In [77]:
a = np.array([[2,4],[6,7]])
a

array([[2, 4],
       [6, 7]])

In [79]:
a + 6
# 相当于自动匹配了一个2*2的6的矩阵然后加上去

array([[ 8, 10],
       [12, 13]])

In [82]:
x = np.arange(4) # 生成一个顺序序列
xx = x.reshape(4,1) #变成一列
y = np.ones(5)
z = np.ones((3,5))

In [85]:
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
# python 有的时候会吧矩阵自动补全然后相加减
y = np.array([[0],[10],[20],[30]])
z = np.array([0,1,2])
y+z
#要嘛有一边对上要嘛两个都是单列的！！！！

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Index

In [88]:
A = np.arange(30).reshape(6,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [93]:
A[0] #the first row

array([0, 1, 2, 3, 4])

In [98]:
A[:,3] #the third column

array([ 3,  8, 13, 18, 23, 28])

In [99]:
A[:,0:3] #select the first three column

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22],
       [25, 26, 27]])

In [100]:
#get odd row
A[1::2,:] #或者不用写第二个维度A[1::2]也行

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

# array Bool

In [101]:
B = np.arange(6)
B

array([0, 1, 2, 3, 4, 5])

In [102]:
# a list of boolean
mask = np.array([True, False,True, False,True, False])
mask

array([ True, False,  True, False,  True, False])

In [103]:
B[mask]
# 则会返回Ture的值

array([0, 2, 4])

In [105]:
B = np.arange(6)
B

array([0, 1, 2, 3, 4, 5])

In [106]:
B>3
# 则会返回真的大于三的位置

array([False, False, False, False,  True,  True])

In [111]:
a = np.random.rand(4,4)
a

array([[0.64732833, 0.986735  , 0.79232972, 0.35399799],
       [0.14551591, 0.10991539, 0.44490858, 0.44322605],
       [0.40419291, 0.04577573, 0.34505992, 0.38751463],
       [0.15470507, 0.22767606, 0.88666194, 0.28128896]])

In [115]:
b = a>0.5
b
# 返回一个指示满足条件的map

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [116]:
a[b]
# 用这个map筛选满足条件的值

array([0.64732833, 0.986735  , 0.79232972, 0.88666194])

In [132]:
# Another way of slicing
indices = [1,3,4]
A[:,[1,3,4]] # 只能取某几行或某几列
#若要取特定行列数字不同则会报错

array([[ 1,  3,  4],
       [ 6,  8,  9],
       [11, 13, 14],
       [16, 18, 19],
       [21, 23, 24],
       [26, 28, 29]])

In [133]:
A[:,[1,3,4]][[2,4],:] #把上一个去的当做一个新的array去取

array([[11, 13, 14],
       [21, 23, 24]])

In [128]:
A[[1,2,3],[1,3,4]] #要一起取的话只能取三个值，它当场坐标来取

array([ 6, 13, 19])

# Boolean Function

In [134]:
A = np.eye(5)
np.any(A)
# if any value is true than returns true

True

In [135]:
B = np.zeros(5)
np.any(B)

False

In [137]:
# quickly check any condition
A = np.arange(5)
np.any(A>4)

True

In [140]:
# if all value if true than return true
np.all(A>1)

False

In [142]:
A = np.arange(30).reshape(5,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### Important

In [150]:
np.any(A % 8 == 0, axis = 1)
# axis = 0 是横着选的，对每一行进行any操作
# axis = 1 是竖着选的，对每一列进行any操作返回一个数列
# 所以any指的就是这个n维数组的第几个轴，然后前面是条件
# 用这个可以很快的得到具体每一行列是否含有满足条件的值！！！！！！！！！！！！！！！！！！

array([ True,  True,  True, False,  True])

In [151]:
np.sum(A,axis = 1)
# 把每一行加起来

array([ 15,  51,  87, 123, 159])

In [153]:
# arg function returns the index
A = A + 10
A

array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [155]:
np.argmax(A)
#返回的是这个faltten的index

29

In [156]:
# 然后就可以用这个index算出二维数组的位置
A[29//6,29%6]
#[整除，余数]

49

In [161]:
np.nonzero(A==49)
#它会返回一个type

(array([4], dtype=int64), array([5], dtype=int64))

In [163]:
# 然后这样就可以get它的实际index
np.nonzero(A==49)[0][0],np.nonzero(A==49)[1][0]

(4, 5)

In [ ]:
# where function....???????
# 看看documentation
# olaolaolaolao