In [2]:
import numpy as np
result = np.array([])

In [3]:
n = np.array([1])
n

array([1])

In [4]:
np.append(n,1)

array([1, 1])

In [5]:
np.array([5])

array([5])

In [9]:
def add_frame(num,arr):
    arr2 = np.pad(arr,((1,1),(1,1)),'constant',constant_values = (num,num))
    return arr2

arr2 = np.array([5])

add_frame(4,arr2)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (1,2)

In [10]:
5 % 2

1

In [23]:
board = np.zeros((8,8))
board[::2,:] = 1
board[:,::2] = 1
board[1::2,:] = 0
board[:,1::2] = 0
board[1::2,1::2] = 1
m = board < 1
board[m]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
3.1 % 3

0.10000000000000009